### ISSUE TITLE
Issues after Rails 4 upgrade

### ISSUE THREAD

**Issue by Blandinium** [lenny/log4jruby#1]
log4jruby worked fine in my Rails 3 application, but after my upgrade to rails 4, I needed to make 2 changes to my initializer to keep things running.
- I needed to wrap the log4jruby logger in a ActiveSupport::TaggedLogging
- I had to add a getter and setter for the formatter

I'm quite new to Ruby and to Rails. But in case this helps anyone: with this config/initializers/log4j.rb, log4jruby works fine for me in rails4.

require 'log4jruby'

def set_logger(framework, logger)
  begin
    Kernel.const_get(framework).const_get('Base').logger = logger
  rescue
    logger.info "Skipping logger setup for #{framework}"
  end
end

class Log4jruby::Logger
  def formatter=(formatter)
    @formatter = formatter
  end
  def formatter
    @formatter
  end
end

Log4jruby::Logger.root.tracing = false
logger = ActiveSupport::TaggedLogging.new(Log4jruby::Logger.get("ichnaea-admin"))

set_logger('ActionController', logger)
set_logger('ActiveRecord', logger)
set_logger('ActiveResource', logger)
set_logger('ActionMailer', logger)

**Comment by lenny** [comment]
https://github.com/lenny/log4jruby/commit/db7e4af52e57da62edf137cbc8ff4dea44a372f0
