### ISSUE TITLE
logger info

### ISSUE THREAD

**Issue by c0mrade** [lenny/log4jruby#12]
I've added your logger to my rails project, why is the logger logging a `DEBUG` level as default? And how do I change it to info? I've tried nothing has worked

This is my initializer :
```
if ENV['ENABLE_LOG4J'] == 'true'
  require 'log4jruby'
end
```

Properties :
```
log4j.appender.MyApp=org.apache.log4j.DailyRollingFileAppender
log4j.appender.MyAppFile=${catalina.base}/logs/myApp.log
log4j.appender.MyApp.Append=true
log4j.appender.MyApp.Encoding=UTF-8
# Roll-over the log once per day
log4j.appender.MyApp.DatePattern="'.'yyyy-MM-dd"
log4j.appender.MyApp.layout = org.apache.log4j.PatternLayout
# log4j.appender.MyApp.layout.ConversionPattern = %d [%t] %-5p %c- %m%n
log4j.appender.MyApp.layout.ConversionPattern=%5p %c %X{methodName}:%X{lineNumber} - %m%n

log4j.logger.jruby=INFO, MyApp
log4j.additivity.jruby=false
```

**Comment by olnrao** [comment]
This is just a thin wrapper over log4j JAR.  I believe there is some other log4j.properties file that is loaded by log4j JAR than yours.  Enable -Dlog4j.debug to get more insight on how log4j is initializing itself.

**Comment by c0mrade** [comment]
thanks you're correct there was another `log4j.properties` located in the `lib` directory of my tomcat server

**Comment by olnrao** [comment]
Good to know it helped.  Please close this ticket.
