### ISSUE TITLE
Bundler::GemRequireError: There was an error while trying to load the gem 'log4jruby'.

### ISSUE THREAD

**Issue by richardsondx** [lenny/log4jruby#15]
jruby-1.7.12
Rails 3.2.13

$ bundle exec rails c
Bundler::GemRequireError: There was an error while trying to load the gem 'log4jruby'.
  require at /Users/john/.rvm/gems/jruby-1.7.12@testapp/gems/bundler-1.11.2/lib/bundler/runtime.rb:81
     each at org/jruby/RubyArray.java:1613
  require at /Users/john/.rvm/gems/jruby-1.7.12@testapp/gems/bundler-1.11.2/lib/bundler/runtime.rb:72
     each at org/jruby/RubyArray.java:1613
  require at /Users/john/.rvm/gems/jruby-1.7.12@testapp/gems/bundler-1.11.2/lib/bundler/runtime.rb:61
  require at /Users/john/.rvm/gems/jruby-1.7.12@testapp/gems/bundler-1.11.2/lib/bundler.rb:99
   (root) at /Users/john/Work/ContactMonkey/cm-emailtrack/config/application.rb:12
  require at org/jruby/RubyKernel.java:1065
   (root) at /Users/john/.rvm/gems/jruby-1.7.12@testapp/gems/railties-3.2.13/lib/rails/commands.rb:1
  require at org/jruby/RubyKernel.java:1065
   (root) at script/rails:6

**Comment by richardsondx** [comment]
+1

**Comment by sybind** [comment]
+1

**Comment by lenny** [comment]
Sounds like you haven't properly loaded/configured log4j before loading log4jruby. Had a section about that in the README. I just released log4jruby-2.0.0. No functional changes over rc3, but I did amend the README a bit. Please refer to that and let me know if you still have any trouble.

**Comment by lenny** [comment]
We use log4jruby with Rails 4.2 and above without issue. Please re-open if this can still be reproduced with the latest version after previous suggestions have been tried.
