### ISSUE TITLE
Rails4 and ActiveRecord_Session_Store

### ISSUE THREAD

**Issue by jkuchta** [lenny/log4jruby#9]
I am trying to upgrade to Rails4 and use ActiveRecord_Session_Store but receive and error:
ArgumentError (wrong number of arguments calling `capture` (0 for 1)):

I believe this is because I am unable to implement the required silencer. (MyLogger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer) from https://github.com/rails/activerecord-session_store

**Comment by lenny** [comment]
This should be addressed in v2.0.0.rc3

See: https://github.com/lenny/log4jruby/pull/11

Please reopen if not resolved.

Thanks,
-lenny
